# ===== Server =====
server.port=${PORT:8080}

# ===== PostgreSQL (Render/Railway/Supabase) =====
spring.datasource.url=${jdbc:postgresql://dpg-d9i5hhbh2c0s73874omg-a.ohio-postgres.render.com:5432/recoverease}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${recoverease_user}
spring.datasource.password=${7DE6W6VIR4RJwnj1lYIm9hWn3VFFdZ3k}

# ===== JPA =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===== H2 OFF in prod =====
spring.h2.console.enabled=false

# ===== JWT =====
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ===== Google Gemini API =====
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# ===== CORS =====
frontend.url=${FRONTEND_URL}

# ===== Logging =====
logging.level.com.recoverease=INFO
logging.level.org.springframework.security=WARN
